### ISSUE TITLE
StateTL - enable data folders and command line arguments

### ISSUE THREAD

**Issue by kelleythompson** [OpenCDSS/ArkDSS-Colors-of-Water#14]
For the CoW project, it may be favorable to run the matlab model engine code using data folders and command line arguments - particularly for calibration. For calibration, this would enable use of one set of executable codes and input and intermediate data files in a base folder, but input and output for a particular calibration parameter change would be maintained in a seperate folder. Command line arguments would also facilitate calibration as well as potentially be used to run the model engine in different ways once deployed

**Comment by kelleythompson** [comment]
Enhancements were initially developed. With folders, one set of executable codes and input and intermediate data files can be maintained in a base folder, but for a particular calibration run a data folder will be created and an inputfile containing a changed input parameter will be placed in that folder.  When the model engine is run, it will use that folder and place all output and logfiles in that data folder.  The j349 input/outfiles as created for and by the fortran code will also be in the data folder.  Some intermediate binary data folders may also be used by the model engine - so it will copy those over to the data folder to avoid any potential file open/sharing issues.  Then command line arguments would also be favorable to allow direction of the model engine without needing to use/change the control file which can be generally be left static and unchanged.  See readme file for notes on usage of command lines arguments.

**Comment by kelleythompson** [comment]
Particularly for calibration process, may be nice to also add command line option to rebuild binary files to prep a year prior to calibration runs

**Comment by kelleythompson** [comment]
Additional command line arguments were developed and refined.  Command line option arguments include `-f -c -b -r -s -d -nd -w -nw` to trigger folder, calibration, build base files, save, display, and write options.  See readme file for examples.

For calibration, example expected command line arguments are:

`StateTL -b 2018` - build new binary base files for full year 2018

`StateTL -f \calibration\Par.1 -c 2018,WD17` - calibrate year 2018 for WD17 with input/output into Par.1 folder

**Comment by smalers** [comment]
Just a comment on standards before people get set on options that may not follow the standards.

* Single dash multi-letter options are ambiguous.  For example, `-nd` could be interpreted as shorthand for `-n` and `-d`.  The standard way of doing this is to use double dashes for multi-character options, as in `--nd`.  These standards help applications be consistent.
* `-h` and `--help` are often used to print program usage, so you don't need to track down documentation.  I recommend enabling this.
* `-v` and `--version` are often used for version
* `-d` and `--debug` are often used to turn on debug, sometimes followed by a level

See [Standards for Command Line Interfaces](https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html)

It is possible to call C routines from Fortran so the above could be used.   I did not do this for StateMod and StateCU because of lack of time.

**Comment by kelleythompson** [comment]
Steve,
Somehow I knew you were going to catch the -nd and -nw.  I couldn't get
creative enough to think of a different letter but I'll sort out a
different way for those options.  But very great points on -h -v and not
using -d.  Thanks for those thoughts and the additional information, and
I'll revise and add to these in a bit.
Thanks a bunch,
Kelley



*Kelley L. Thompson, P.E.*
*Senior Lead Modeler - Modeling and DSS / Water Information Team*

P 303.866.3581 ext 8261 |  C 719.480.3423
1313 Sherman St., Suite 818, Denver, CO  80203
***@***.***  |  www.water.state.co.us
